# Site Settings
title: My Jekyll Site
description: A simple Jekyll site deployed to GitHub Pages.
url: "https://lucasischow.github.io"  # Replace with your GitHub Pages URL
baseurl: "lucasischow.github.io"  # Use "/repository-name" for project pages

# Markdown Processor
markdown: kramdown

# Exclude files and folders
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - .git
  - .github

# Include the _next directory (necessary for Next.js static files)
include:
  - _next
 
# Keep files/folders that shouldn't be processed by Jekyll (like static assets)
keep_files:
  - _next  # Ensures _next folder is copied as-is
