name: anderson_shop
description: anderson online shop application

publish_to: 'none'

version: 1.1.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter_inappwebview: 5.4.3+7
  carousel_slider: ^4.1.1
  photo_view: ^0.14.0
  fluttertoast: ^8.0.9
  dio: ^4.0.6
  localstore: ^1.2.3
  url_launcher: ^6.1.3
  flutter_launcher_icons: ^0.9.3

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  #  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launchIcons/ic_launcher.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
